---
- name: Add the webupd8 APT repository
  apt_repository: repo="deb http://ppa.launchpad.net/webupd8team/java/ubuntu precise main" state=present

- name: Automatically select the Oracle License
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  changed_when: false

- name: Install Oracle Java
  apt: name={{item}} state=present force=yes state=latest update_cache=yes cache_valid_time=3600
  with_items:
  #- oracle-java8-installer
  - openjdk-8-jre-headless
  - openjdk-8-jdk-headless

- name: Set JAVA_HOME
  lineinfile:
    dest: /etc/environment
    state: present
    regexp: '^JAVA_HOME'
    line: 'JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64'
  #shell: sudo echo "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> ~/.bashrc
  #shell: echo JAVA_HOME is $JAVA_HOME
  #environment:
  #  JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
  #register: shellout
